### ISSUE TITLE
파일 크기 전송

### ISSUE THREAD

**Issue by HonggabKim** [cykim2129/scpy_project#2]
파일 데이터을 보내기 전에 파일 전체 크기를 전송하고, 수신 후 전체 크기를 비교할 것

**Comment by cykim2129** [comment]
수신 완료후 마지막에 

  if(bytes_received == file_size){
        file.close();
        } else {
        	std::cout << "파일 수신 중 파일데이터 오류 발생" << std::endl;
        	file.close();
        	close(serial_fd);
        	return;  
        }
파일사이즈랑 수신 받은 사이즈 비교하는 코드 추가하였습니다.
